#!/HDD_bni/1_git_projects/VirEnv/5_OmegaFold/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from omegafold.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
